spring:
  application:
    name: sunaba
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/sunaba_mysql
    username: root
    password: root_password
  flyway:
    enabled: true